### ISSUE TITLE
Images are broken when pushed to production

### ISSUE THREAD

**Issue by realChakrawarti** [DaveAldon/Next.js-and-GitHub-Pages-Example#4]
![image](https://github.com/DaveAldon/Next.js-and-GitHub-Pages-Example/assets/105297743/11ff0b29-21f9-460e-b72d-fa1b10b83270)

You can see the vercel logo at the bottom isn't loading.

- The current path of the image is: https://davealdon.github.io/vercel.svg
- The path should have been: https://davealdon.github.io/Next.js-and-GitHub-Pages-Example/vercel.svg

**Comment by realChakrawarti** [comment]
The issue arises for all assets in public directory.

**Comment by DaveAldon** [comment]
Thanks for calling that out. This should be fixed now with PR https://github.com/DaveAldon/Next.js-and-GitHub-Pages-Example/pull/5.

Images using the Nextjs `<Image/>` component aren't as quite "out of the box" as they used to be with asset prefixes. It unfortunately needs some manual work, but I've tried to offer a solution that's easy enough to use.
